# Generated by Django 5.1.6 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис стрінки з проектами')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='Мета-опис стрінки з проектами')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Мета-опис стрінки з проектами')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
            ],
            options={
                'verbose_name': 'Метаопис сторінки проектів',
                'verbose_name_plural': 'Метаопис сторінки проектів',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Назва')),
                ('short_description', models.TextField(max_length=500, verbose_name='Короткий опис')),
                ('short_description_uk', models.TextField(max_length=500, null=True, verbose_name='Короткий опис')),
                ('short_description_en', models.TextField(max_length=500, null=True, verbose_name='Короткий опис')),
                ('full_description', models.TextField(verbose_name='Повний опис')),
                ('full_description_uk', models.TextField(null=True, verbose_name='Повний опис')),
                ('full_description_en', models.TextField(null=True, verbose_name='Повний опис')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Зображення')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис стрінки проекту')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('services', models.ManyToManyField(related_name='projects', to='services.service', verbose_name='Послуги')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
    ]
