# Generated by Django 5.1.6 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блоку з відгуками')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з відгуками')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з відгуками')),
                ('link_text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('link_text_uk', models.CharField(max_length=255, null=True, verbose_name='Текст кнопки')),
                ('link_text_en', models.CharField(max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправлення')),
            ],
            options={
                'verbose_name': "Форма зворотного зв'язку",
                'verbose_name_plural': "Форма зворотного зв'язку",
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_text_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero секция',
                'verbose_name_plural': 'Hero секция',
            },
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('caption', models.TextField(verbose_name='Опис')),
                ('caption_uk', models.TextField(null=True, verbose_name='Опис')),
                ('caption_en', models.TextField(null=True, verbose_name='Опис')),
                ('span', models.CharField(max_length=100, verbose_name='Фіналочка')),
                ('span_uk', models.CharField(max_length=100, null=True, verbose_name='Фіналочка')),
                ('span_en', models.CharField(max_length=100, null=True, verbose_name='Фіналочка')),
                ('stats', models.JSONField(default=list, verbose_name='Stats')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_text_uk', models.CharField(max_length=100, null=True, verbose_name='Текст кнопки')),
                ('button_text_en', models.CharField(max_length=100, null=True, verbose_name='Текст кнопки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Інформаційна секція',
                'verbose_name_plural': 'Інформаційна секція',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис головної сторінки')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='Мета-опис головної сторінки')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Мета-опис головної сторінки')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('meta_keywords_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
            ],
            options={
                'verbose_name': 'Метаопис головної сторінки',
                'verbose_name_plural': 'Метаопис головної сторінки',
            },
        ),
        migrations.CreateModel(
            name='ProjectsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блоку з проектами')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з проектами')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з проектами')),
                ('link_text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
                ('link_text_uk', models.CharField(max_length=255, null=True, verbose_name='Текст кнопки')),
                ('link_text_en', models.CharField(max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Секція проектів',
                'verbose_name_plural': 'Секція проектів',
            },
        ),
        migrations.CreateModel(
            name='ReviewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блоку з відгуками')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з відгуками')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з відгуками')),
                ('caption', models.TextField(max_length=255, verbose_name='Опис')),
                ('caption_uk', models.TextField(max_length=255, null=True, verbose_name='Опис')),
                ('caption_en', models.TextField(max_length=255, null=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Секція відгуків',
                'verbose_name_plural': 'Секція відгуків',
            },
        ),
        migrations.CreateModel(
            name='ServicesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блоку з послугами')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з послугами')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок блоку з послугами')),
                ('link_text', models.CharField(default='Детальніше', max_length=255, verbose_name='Текст кнопки')),
                ('link_text_uk', models.CharField(default='Детальніше', max_length=255, null=True, verbose_name='Текст кнопки')),
                ('link_text_en', models.CharField(default='Детальніше', max_length=255, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Секція послуг',
                'verbose_name_plural': 'Секція послуг',
            },
        ),
    ]
