# Generated by Django 5.1.6 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис сторінки з послугамі')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки з послугамі')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки з послугамі')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('meta_keywords_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
            ],
            options={
                'verbose_name': 'Метаопис сторінки послуг',
                'verbose_name_plural': 'Метаопис сторінки послуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('short_title', models.CharField(max_length=50, verbose_name='Short title')),
                ('short_title_uk', models.CharField(max_length=50, null=True, verbose_name='Short title')),
                ('short_title_en', models.CharField(max_length=50, null=True, verbose_name='Short title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_uk', models.TextField(null=True, verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Image')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис послуги')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['-created_at'],
            },
        ),
    ]
