# Generated by Django 5.1.6 on 2025-02-07 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_uk', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Image')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис сторінки статті')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published At')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис сторінки блогу')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки блогу')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки блогу')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова сторінки блогу')),
                ('meta_keywords_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова сторінки блогу')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова сторінки блогу')),
            ],
            options={
                'verbose_name': 'Метаопис сторінки блогу',
                'verbose_name_plural': 'Метаопис сторінки блогу',
            },
        ),
    ]
