# Generated by Django 5.1.6 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_uk', models.TextField(null=True, verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-опис сторінки про нас')),
                ('meta_description_uk', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки про нас')),
                ('meta_description_en', models.TextField(blank=True, null=True, verbose_name='Мета-опис сторінки про нас')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключові слова')),
                ('meta_keywords_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
                ('meta_keywords_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключові слова')),
            ],
            options={
                'verbose_name': 'Про нас',
                'verbose_name_plural': 'Про нас',
            },
        ),
    ]
